import { strings } from "@angular-devkit/core";
import { dasherize } from "@angular-devkit/core/src/utils/strings";
import {
  apply,
  applyTemplates,
  chain,
  MergeStrategy,
  mergeWith,
  noop,
  Rule,
  schematic,
  SchematicContext,
  Tree,
  url,
} from "@angular-devkit/schematics";

import { Schematic } from "@enums/Schematic";
import { stubArg } from "@janush-schematics/utility/stubArg/stubArg";

import { Schema } from "./schema";

export const isCloud = (options: Schema) => options.types.includes(Schematic.CLOUD);
export const isWeb = (options: Schema) => options.types.includes(Schematic.WEB);

export const applicationGenerator = (options: Schema): Rule => {
  return (_: Tree, _context: SchematicContext) => {
    const scope = dasherize(options.name);

    return chain([
      mergeWith(
        apply(url("./files"), [
          applyTemplates({
            ...options,
            ...strings,
          }),
        ]),
        MergeStrategy.Overwrite,
      ),
      options.isAutoGenerated
        ? mergeWith(
            apply(url("./filesCi"), [
              applyTemplates({
                ...options,
                ...strings,
              }),
            ]),
            MergeStrategy.Overwrite,
          )
        : stubArg,
      isCloud(options) ? schematic(Schematic.CLOUD, options, { scope }) : noop(),
      isWeb(options) ? schematic(Schematic.WEB, options, { scope }) : noop(),
      schematic("applyPrettier", {}, { scope }),
    ]);
  };
};
